# ==============================================================================
# Yazi Configuration File (yazi.toml)
# ==============================================================================

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Neovim", for = "unix" }
]

